#!/bin/sh
DIR=/home/pi/github/basic-bot
cd $DIR

if [ -f .env ]; then
  source .env
fi

if [ -n "$(pidof node)" ]
then
  killall node
fi

#$DIR/motionMaker.sh

export PATH=$PATH:$DIR/node_modules/.bin
coffee app.coffee > $DIR/bot.log 2>$DIR/err.log &

#ssh -N -R 25225:localhost:3000 hcwiley@hcwiley.com -f
